export default {
  helpMenuLabel: 'Help & Support',
  helpMenuTutorials: 'Tutorials',
  helpMenuReference: 'Reference',
  helpMenuChangelog: 'Changelog',
  helpMenuCreateSupportTicket: 'Create support ticket',
  helpMenuGiveFeedback: 'Give feedback',

  mobileMenuButtonTitle: 'Menu',

  sidebarMainGroupLabel: 'Application',
  sidebarHomeLabel: 'Home',
  sidebarWelcomeLabel: 'Welcome',
  sidebarCreateLabel: 'Create',
  sidebarPublicLabel: 'Public',
  sidebarPublicWorkflowsLabel: 'Public workflows',
  sidebarMyWorkflowsLabel: 'My workflows',
  sidebarTemplatesLabel: 'My templates',
  sidebarSearchLabel: 'Search',
  sidebarSettingsLabel: 'Settings',
  sidebarAdminLabel: 'Admin',
  sidebarRecentItemsLabel: 'Recent Items',
  sidebarTagsLabel: 'Tags',
  sidebarNoRecentItems: 'No recent items',
  sidebarNoTags: 'No tags',
  sidebarBuild: 'build',

  buttonCancel: 'Cancel',
  cancel: 'Cancel',
  OK: 'OK',
  save: 'Save',

  loginForgotPassword: 'Forgot password?',
  loginSignUp: 'Register',
  loginTitle: 'Log In',
  usernameOrEmail: 'Email or Username',
  usernameOrEmailRequired: 'Email or Username are required',
  username: 'Username',
  email: 'Email',
  password: 'Password',
  version: 'Version',
  signupTitle: 'Apply for waitlist',
  usernameRequired: 'Username is required',
  usernameCannotContainAtSymbol: 'Username must not contain @ symbol',
  fieldHaveSpacesBetweenChars: 'The field must not have spaces between the characters',
  emailRequired: 'Email is required',
  invalidEmailAddress: 'Provide a valid email address',
  passwordRequired: 'Password is required',
  passwordMinLength: 'Password must be at least 7 characters long',
  invalidPassword: 'Must contain 8 characters, one uppercase, one number and one special character',
  alreadyExistAccount: 'Already have an account?',
  notRegistered: 'No account yet?',
  createAccount: 'Create Account',
  signupDialogTitle: 'Welcome aboard!',
  signupDialogMessage: "Your account is awaiting approval. We'll notify you shortly.",

  accountRecovery: 'Account Recovery',
  sendRecoveryLink: 'Send recovery link',
  forgotPasswordDialogTitle: 'Check Your Inbox!',
  forgotPasswordDialogMessage:
    "A password reset email has been sent to your email address. Once you receive the email, open the link provided to reset your password.<br><br>If you don't see the email in your inbox, please also check your spam folder.",
  noDataAvailable: 'No data available',
  resetPassword: 'Reset Password',
  reset: 'Reset',
  passwordChanged: 'Password has been successfully changed',

  noUsersInWaitlist: 'No users in the waitlist',
  pageTitle: {
    adminCRM: 'User Stats',
    adminWaitlist: 'Waitlist',
    settings: 'Settings',
  },

  userProfileUserId: 'User Id',
  userProfileName: 'Name',
  userProfileMail: 'Mail',
  userProfileWordpressProfile: 'Wordpress Profile',
  userProfileWorkflowCount: 'Workflow Count',
  userProfileSharedWorkflows: 'Shared Workflows',
  userProfileSharedWithCount: 'Shared With Count',
  userProfileNodeCount: 'Node Count',
  userProfileEdgeCount: 'Edge Count',
  userProfileMaxNodeCount: 'Max Node Count',
  userProfileNodeLimit: 'Node Limit',
  userProfileFreeNodes: 'Free Nodes',
  userProfileSubscriber: 'Subscriber',
  userProfileCreatedAt: 'Created At',
  userProfileLastWorkflowChange: 'Last Workflow Change',
  userProfileDeleteUser: 'Delete User',
  userProfileDeleteConfirmationTitle: 'User delete confirmation',
  userProfileDeleteConfirmationQuestion:
    'You are about to delete the user account associated with {username}. This action is irreversible and will permanently remove all associated user data. Please confirm that you want to proceed with the deletion.',
  userProfileDeleteSuccess: 'User was successfully removed',
  yes: 'Yes',
  no: 'No',
  confirm: 'Confirm',
  back: 'Back',
  comment: 'Comment',

  errorRequestHandling: 'A server error occurred.',
  errorServer: 'A server error occurred. Please try again later.',
  errorLogin: 'Username or password is incorrect.',
  errorInvalidServerMessage: 'Received invalid server response.',
  errorRuntime: 'An error occurred while handling your request.',
  errorLoginPassword: 'Password incorrect.',
  errorLoginUsername: 'Unknown username.',
  errorErrorToBackendSuccess: 'Successfully submitted error for further investigation',
  errorUnknown: 'Unknown error occurred.',
  errorNoPermissions: 'No permissions found',
  errorList: 'Error List',
  error404: 'The page you requested was not found.',
  adminList: 'User Stats',
  adminWaitlist: 'Waitlist',

  menuItemTraining: 'Training',
  comingSoon: 'Coming soon',
  landingWelcomeTitle: 'Welcome to Delta5',
  landingWelcomeDescription: 'Create, manage, and share workflows with ease',
  landingLoginButton: 'Login',
  landingSignUpButton: 'Sign Up',
  allAccountApproved: 'All accounts approved',
  activationError: 'Activation Error',
  accountApproved: 'Account approved',
  approveAll: 'Approve All',
  rejectAll: 'Reject All',
  allAccountRejected: 'Accounts removed from the waitlist',
  rejectError: 'Rejection operation failed',
  accountRejected: 'Account rejected',
  approve: 'Approve',
  reject: 'Reject',

  admin: {
    crm: {
      userProfile: {
        commentSaveSuccess: 'Your comment was saved successfully',
      },
      waitlist: {
        ActivateAccountSuccess: 'Account has been activated successfully',
        ActivateAccountError: 'Failed to activate',
      },
    },
  },

  integrationSettings: {
    appsIntegrations: 'Integrations',
    addApps: 'Add integration',
    none: 'No integrations yet',
  },
  integration: {
    openai: {
      title: 'OpenAI ChatGPT',
      installed: 'Installed',
    },
    yandex: {
      title: 'Yandex GPT',
      installed: 'Installed',
    },
    claude: {
      title: 'Claude',
      installed: 'Installed',
    },
    perplexity: {
      title: 'Perplexity',
      installed: 'Installed',
    },
    qwen: {
      title: 'Qwen',
      installed: 'Installed',
    },
    deepseek: {
      title: 'Deepseek',
      installed: 'Installed',
    },
    custom_llm: {
      title: 'Custom LLM',
    },
    installed: 'Installed',
  },

  dialog: {
    integration: {
      title: 'Available integrations',
      apiKey: 'API key',
      folderId: 'Folder ID',
      model: 'Model',
      otherSettings: 'Other settings',
      saveSuccess: 'Integration changes have been applied successfully!',
      authenticationError: 'Please double-check your API key and its validity',
      genericError: "Something went wrong. Please check the Network logs in  your browser's developer tools",
      rateLimitExceeded: 'You have exceeded your current quota, please check your plan and billing details',
      serverError: 'Model or server is overloaded. Please try again later',
      wrongRequest: 'Something went wrong with the request, please check the network log',
      noAccess: 'You have no access to {model}',
      wrongFolderId: 'Please double-check your Folder ID',
    },
  },

  apiRootUrl: 'API Root URL',
  maxTokens: 'Max Tokens',
  apiType: 'API Type',
  embeddingsChunkSize: 'Embeddings Chunk Size',
  customLLMHint: 'Hint: use `/custom` command to trigger this integration',

  profileSettings: {
    applyChanges: 'Apply Changes',
    emailAddress: 'Email Address',
    editProfile: 'Edit Profile',
    appsIntegrations: 'Integrations',
    username: 'Username',
    success: 'Success',
    unknown: 'Unknown',
    model: 'Model',
  },

  defaultLang: 'Auto based on language',
  noLanguage: 'No language found',
  default: 'Default',
  lang: 'Language',

  langSaveSuccessfully: 'Language saved successfully',
  modelSaveSuccessfully: 'Model saved successfully',

  themeLabel: 'Theme',
  themeLight: 'Day',
  themeDark: 'Night',
  themeSystem: 'Auto based on OS',

  createWorkflow: 'Create workflow',
  callToRegisterTitle: 'Create your own workflows',
  buttonRegister: 'Signup For Free',

  homePublicText: 'Public workflows',
  homePrivateText: 'My workflows',
  workflowTemplates: 'My templates',
  createWorkflowFromTemplate: 'Create workflow from template',
  tabAll: 'All',
  tabPrivate: 'Private',
  tabPublic: 'Public',
  tabPublicUnlisted: 'Unlisted',

  workflowTitle: 'Name',
  workflowShared: 'Shared',
  workflowCreating: 'Creating a new workflow',
  workflowLoading: 'Loading workflow',
  workflowIsPublic: 'Public',
  workflowCardCreated: 'created',
  workflowCardUpdated: 'updated',
  workflowCardTimeAgo: 'ago',
  menuDeleteWorkflow: 'Delete',
  menuExportWorkflow: 'Export',
  menuVisibility: 'Set Visibility',
  workflowAddCategoryLabel: 'Add Category',
  workflowAddDashboardLabel: 'Add Dashboard',

  dialogWorkflowPrivacyOpenerTitle: 'Change Privacy',
  dialogWorkflowPrivacyMessage: 'Choose here how your workflow can be found, viewed or edited by others:',
  dialogWorkflowPrivacyTitle: 'Sharing / Visibility',
  buttonShare: 'Public',
  buttonShareWritable: 'Public Writeable',
  buttonShareWritableMessage: 'Everyone can edit it (Administrators only)',
  buttonShareWritableHidden: 'Public Unlisted Writeable',
  buttonShareWritableHiddenMessage: 'Everyone with the link to the workflow can edit it',
  buttonShareMessage: 'Everyone can find it in the list of public workflows',
  buttonShareHidden: 'Public Unlisted',
  buttonShareHiddenMessage: 'Everyone with the workflow link can view your workflow',
  buttonUnshare: 'Private',
  buttonUnshareMessage: 'Only you can view this workflow',
  shareSuccessChange: 'Workflow visibility changed successfully',
  categoryCreatedSuccesfully: 'Worfkwlo category created successfully',
  workflowDeleteSuccessful: 'Your workflow was successfully deleted',

  delete: 'Delete',
  deleteWorkflowWarning: 'To confirm, type “{title}” below:',
  deleteWorkflowMessage: 'This action cannot be undone. Please confirm by typing the workflow name',
  deleteWorkflowDialogTitle: 'Delete workflow?',

  noWorkflowsYet: 'There are no workflows here yet',
  updated: 'Updated',
  created: 'Created',
  workflowIsHidden: 'Public Unlisted',
  workflowIsPrivate: 'Private',
  searchWorkflow: 'Search workflow',
  workflowsPublic: 'Public workflows',
  workflowsPrivate: 'My workflows',
  emptyWorkflow: 'Empty workflow',
  createNewWorkflow: 'Create a new workflow',
  prev: 'Previous',
  next: 'Next',
  actions: 'Actions',
  downloadCSV: 'Download CSV',
  morePages: 'More pages',
  userSettingsMenuSignedIn: 'Signed In',
  logout: 'Log out',
  surveyData: 'Survey Data',
  workflowId: 'Workflow (Id)',
  close: 'Close',

  settingsPageProfile: 'Profile',
  settingsPageIntegrations: 'Integrations',
  loadingPlaceholder: 'Loading...',
  toggleSidebar: 'Toggle Sidebar',
  toggleSecondaryMenu: 'Toggle Secondary Menu',
  rowsPerPage: 'Rows per page',
  page: 'Page',

  copy: 'Copy',
  copied: 'Copied!',

  share: 'Share',
  shareWorkflow: 'Share Workflow',
  shareWorkflowTitle: 'Share Workflow',
  shareWorkflowDescription: 'Share your workflow with others via link or QR code',
  shareLink: 'Link',
  showQRCode: 'Show QR Code',
  hideQRCode: 'Hide QR Code',
  downloadQRCode: 'Download QR Code',
  advancedOptions: 'More Options',
  visibilityLabel: 'Visibility',
  visibilitySettings: 'Visibility & Sharing',
  visibilityPublic: 'Public',
  visibilityPrivate: 'Private',
  visibilityUnlisted: 'Unlisted',
  visibilityPrivateDescription: 'Only you can access this workflow',
  visibilityUnlistedDescription: 'Anyone with the link can view',
  visibilityPublicDescription: 'Discoverable and viewable by anyone',
  collaborativeEditing: 'Collaborative editing',
  collaborativeEditingUnlistedDescription: 'Anyone with link can edit',
  collaborativeEditingPublicDescription: 'Anyone can edit',
  workflowSharedPublicSuccess: 'Workflow is now public! Link copied to clipboard.',
  workflowMadePrivateSuccess: 'Workflow is now private',
}
