export default {
  helpMenuLabel: 'Help & Support',
  helpMenuTutorials: 'Tutorials',
  helpMenuTerraformProvider: 'Terraform Provider',
  helpMenuChangelog: 'Changelog',
  helpMenuCreateSupportTicket: 'Create support ticket',
  helpMenuGiveFeedback: 'Give feedback',

  mobileMenuButtonTitle: 'Menu',

  sidebarMainGroupLabel: 'Application',
  sidebarHomeLabel: 'Home',
  sidebarInboxLabel: 'Inbox',
  sidebarCalendarLabel: 'Calendar',
  sidebarSearchLabel: 'Search',
  sidebarSettingsLabel: 'Settings',

  buttonCancel: 'Cancel',
  OK: 'OK',

  loginForgotPassword: 'Forgot password?',
  loginSignUp: 'Register',
  loginTitle: 'Log In',
  usernameOrEmail: 'Email or Username',
  usernameOrEmailRequired: 'Email or Username are required',
  username: 'Username',
  email: 'Email',
  password: 'Password',
  version: 'Version',
  signupTitle: 'Apply for waitlist',
  usernameRequired: 'Username is required',
  fieldHaveSpacesBetweenChars: 'The field must not have spaces between the characters',
  emailRequired: 'Email is required',
  invalidEmailAddress: 'Provide a valid email address',
  passwordRequired: 'Password is required',
  invalidPassword: 'Must contain 8 characters, one uppercase, one number and one special character',
  alreadyExistAccount: 'Already have an account?',
  notRegistered: 'No account yet?',
  createAccount: 'Create Account',
  signupDialogTitle: 'Thank you for signing up!',
  signupDialogMessage:
    '<b>Your account is currently in the waitlist for manual approval.</b> You will receive an email notification once your account has been approved.<br><br><b>We appreciate your patience and look forward to having you as a user of our product!</b>',
}
