export default {
  helpMenuLabel: 'Help & Support',
  helpMenuTutorials: 'Tutorials',
  helpMenuTerraformProvider: 'Terraform Provider',
  helpMenuChangelog: 'Changelog',
  helpMenuCreateSupportTicket: 'Create support ticket',
  helpMenuGiveFeedback: 'Give feedback',

  mobileMenuButtonTitle: 'Menu',

  sidebarMainGroupLabel: 'Application',
  sidebarHomeLabel: 'Home',
  sidebarInboxLabel: 'Inbox',
  sidebarCalendarLabel: 'Calendar',
  sidebarSearchLabel: 'Search',
  sidebarSettingsLabel: 'Settings',

  buttonCancel: 'Cancel',
  OK: 'OK',

  loginForgotPassword: 'Forgot password?',
  loginSignUp: 'Register',
  loginTitle: 'Log In',
  usernameOrEmail: 'Email or Username',
  usernameOrEmailRequired: 'Email or Username are required',
  username: 'Username',
  email: 'Email',
  password: 'Password',
  version: 'Version',
  signupTitle: 'Apply for waitlist',
  usernameRequired: 'Username is required',
  fieldHaveSpacesBetweenChars: 'The field must not have spaces between the characters',
  emailRequired: 'Email is required',
  invalidEmailAddress: 'Provide a valid email address',
  passwordRequired: 'Password is required',
  invalidPassword: 'Must contain 8 characters, one uppercase, one number and one special character',
  alreadyExistAccount: 'Already have an account?',
  notRegistered: 'No account yet?',
  createAccount: 'Create Account',
  signupDialogTitle: 'Thank you for signing up!',
  signupDialogMessage:
    '<b>Your account is currently in the waitlist for manual approval.</b> You will receive an email notification once your account has been approved.<br><br><b>We appreciate your patience and look forward to having you as a user of our product!</b>',

  accountRecovery: 'Account Recovery',
  sendRecoveryLink: 'Send recovery link',
  forgotPasswordDialogTitle: 'Email Sent',
  forgotPasswordDialogMessage:
    "A password reset email has been sent to your email address. Once you receive the email, open the link provided to reset your password.<br><br>If you don't see the email in your inbox, please also check your spam folder. ",
  noDataAvailable: 'No data available',
  resetPassword: 'Reset Password',
  reset: 'Reset',
  passwordChanged: 'Password has been successfully changed',

  noUsersInWaitlist: 'No users in the waitlist',
  pageTitle: {
    adminCRM: 'User Stats',
    adminWaitlist: 'Waitlist',
  },

  userProfileUserId: 'User Id',
  userProfileName: 'Name',
  userProfileMail: 'Mail',
  userProfileWordpressProfile: 'Wordpress Profile',
  userProfileMapCount: 'Map Count',
  userProfileSharedMaps: 'Shared Maps',
  userProfileSharedWithCount: 'Shared With Count',
  userProfileNodeCount: 'Node Count',
  userProfileMaxNodeCount: 'Max Node Count',
  userProfileNodeLimit: 'Node Limit',
  userProfileSubscriber: 'Subscriber',
  userProfileCreatedAt: 'Created At',
  userProfileLastMapChange: 'Last Map Change',
  userProfileDeleteUser: 'Delete User',
  userProfileDeleteConfirmationTitle: 'User delete confirmation',
  userProfileDeleteConfirmationQuestion:
    'You are about to delete the user account associated with {username}. This action is irreversible and will permanently remove all associated user data. Please confirm that you want to proceed with the deletion.',
  userProfileDeleteSuccess: 'User was successfully removed',
  yes: 'Yes',
  no: 'No',
  confirm: 'Confirm',
  back: 'Back',
  comment: 'Comment',

  errorRequestHandling: 'A server error occurred.',
  errorServer: 'A server error occurred. Please try again later.',
  errorLogin: 'Username or password is incorrect.',
  errorInvalidServerMessage: 'Received invalid server response.',
  errorRuntime: 'An error occurred while handling your request.',
  errorLoginPassword: 'Password incorrect.',
  errorLoginUsername: 'Unknown username.',
  errorErrorToBackendSuccess: 'Successfully submitted error for further investigation',
  errorUnknown: 'Unknown error occurred.',
  errorNoPermissions: 'No permissions found',
  errorList: 'Error List',
  error404: 'The page you requested was not found.',
}
