export default {
  helpMenuLabel: 'Помощь и поддержка',
  helpMenuTutorials: 'Руководства',
  helpMenuReference: 'Справочник',
  helpMenuChangelog: 'Журнал изменений',
  helpMenuCreateSupportTicket: 'Создать заявку',
  helpMenuGiveFeedback: 'Оставить отзыв',

  mobileMenuButtonTitle: 'Меню',

  sidebarMainGroupLabel: 'Приложение',
  sidebarHomeLabel: 'Главная',
  sidebarWelcomeLabel: 'Добро пожаловать',
  sidebarCreateLabel: 'Создать',
  sidebarPublicLabel: 'Публичные',
  sidebarPublicWorkflowsLabel: 'Публичные сценарии',
  sidebarMyWorkflowsLabel: 'Мои сценарии',
  sidebarTemplatesLabel: 'Мои шаблоны',
  sidebarSearchLabel: 'Поиск',
  sidebarSettingsLabel: 'Настройки',
  sidebarAdminLabel: 'Администратор',
  sidebarRecentItemsLabel: 'Недавние',
  sidebarTagsLabel: 'Теги',
  sidebarNoRecentItems: 'Нет недавних элементов',
  sidebarNoTags: 'Нет тегов',
  sidebarBuild: 'сборка',

  buttonCancel: 'Отмена',
  cancel: 'Отмена',
  OK: 'ОК',
  save: 'Сохранить',

  loginForgotPassword: 'Забыли пароль?',
  loginSignUp: 'Зарегистрироваться',
  loginTitle: 'Войти',
  usernameOrEmail: 'Email или имя пользователя',
  usernameOrEmailRequired: 'Email или имя пользователя обязательны',
  username: 'Имя пользователя',
  email: 'Email',
  password: 'Пароль',
  version: 'Версия',
  signupTitle: 'Запрос на доступ',
  usernameRequired: 'Имя пользователя обязательно',
  usernameCannotContainAtSymbol: 'Имя пользователя не должно содержать символ @',
  fieldHaveSpacesBetweenChars: 'Поле не должно содержать пробелов между символами',
  emailRequired: 'Email обязателен',
  invalidEmailAddress: 'Укажите корректный email',
  passwordRequired: 'Пароль обязателен',
  passwordMinLength: 'Пароль должен содержать не менее 7 символов',
  invalidPassword: 'Должен содержать 8 символов, одну заглавную букву, цифру и спецсимвол',
  alreadyExistAccount: 'Уже есть аккаунт?',
  notRegistered: 'Ещё нет аккаунта?',
  createAccount: 'Создать аккаунт',
  signupDialogTitle: 'Добро пожаловать!',
  signupDialogMessage: 'Ваш аккаунт ожидает подтверждения. Мы скоро вас уведомим.',

  accountRecovery: 'Восстановление аккаунта',
  sendRecoveryLink: 'Отправить ссылку для восстановления',
  forgotPasswordDialogTitle: 'Проверьте почту!',
  forgotPasswordDialogMessage:
    'Письмо для сброса пароля отправлено на ваш адрес. После получения письма откройте ссылку для сброса пароля.<br><br>Если письмо не в папке «Входящие», проверьте папку «Спам».',
  noDataAvailable: 'Данные отсутствуют',
  resetPassword: 'Сбросить пароль',
  reset: 'Сбросить',
  passwordChanged: 'Пароль успешно изменён',

  noUsersInWaitlist: 'Нет пользователей в списке ожидания',
  pageTitle: {
    adminCRM: 'Статистика пользователей',
    adminWaitlist: 'Список ожидания',
    settings: 'Настройки',
  },

  userProfileUserId: 'ID пользователя',
  userProfileName: 'Имя',
  userProfileMail: 'Почта',
  userProfileWordpressProfile: 'Профиль WordPress',
  userProfileWorkflowCount: 'Количество сценариев',
  userProfileSharedWorkflows: 'Общие сценарии',
  userProfileSharedWithCount: 'Кол-во общих доступов',
  userProfileNodeCount: 'Кол-во узлов',
  userProfileEdgeCount: 'Кол-во связей',
  userProfileMaxNodeCount: 'Макс. кол-во узлов',
  userProfileNodeLimit: 'Лимит узлов',
  userProfileFreeNodes: 'Свободных узлов',
  userProfileSubscriber: 'Подписчик',
  userProfileCreatedAt: 'Создан',
  userProfileLastWorkflowChange: 'Последнее изменение',
  userProfileDeleteUser: 'Удалить пользователя',
  userProfileDeleteConfirmationTitle: 'Подтверждение удаления',
  userProfileDeleteConfirmationQuestion:
    'Вы собираетесь удалить аккаунт пользователя {username}. Это действие необратимо. Подтвердите удаление.',
  userProfileDeleteSuccess: 'Пользователь успешно удалён',
  yes: 'Да',
  no: 'Нет',
  confirm: 'Подтвердить',
  back: 'Назад',
  comment: 'Комментарий',

  errorRequestHandling: 'Произошла ошибка сервера.',
  errorServer: 'Произошла ошибка сервера. Попробуйте позже.',
  errorLogin: 'Неверное имя пользователя или пароль.',
  errorInvalidServerMessage: 'Получен некорректный ответ сервера.',
  errorRuntime: 'Произошла ошибка при обработке запроса.',
  errorLoginPassword: 'Неверный пароль.',
  errorLoginUsername: 'Неизвестное имя пользователя.',
  errorErrorToBackendSuccess: 'Ошибка успешно отправлена на проверку',
  errorUnknown: 'Неизвестная ошибка.',
  errorNoPermissions: 'Нет прав доступа',
  errorList: 'Список ошибок',
  error404: 'Запрошенная страница не найдена.',
  adminList: 'Статистика пользователей',
  adminWaitlist: 'Список ожидания',

  menuItemTraining: 'Обучение',
  comingSoon: 'Скоро',
  landingWelcomeTitle: 'Добро пожаловать в Delta5',
  landingWelcomeDescription: 'Создавайте, управляйте и делитесь сценариями',
  landingLoginButton: 'Войти',
  landingSignUpButton: 'Зарегистрироваться',
  allAccountApproved: 'Все аккаунты подтверждены',
  activationError: 'Ошибка активации',
  accountApproved: 'Аккаунт подтверждён',
  approveAll: 'Подтвердить всех',
  rejectAll: 'Отклонить всех',
  allAccountRejected: 'Аккаунты удалены из списка ожидания',
  rejectError: 'Ошибка отклонения',
  accountRejected: 'Аккаунт отклонён',
  approve: 'Подтвердить',
  reject: 'Отклонить',

  admin: {
    crm: {
      userProfile: {
        commentSaveSuccess: 'Комментарий успешно сохранён',
      },
      waitlist: {
        ActivateAccountSuccess: 'Аккаунт успешно активирован',
        ActivateAccountError: 'Не удалось активировать',
      },
    },
  },

  integrationSettings: {
    appsIntegrations: 'Интеграции',
    addApps: 'Добавить интеграцию',
    none: 'Интеграции отсутствуют',
  },
  integration: {
    openai: {
      title: 'OpenAI ChatGPT',
      installed: 'Установлено',
    },
    yandex: {
      title: 'Яндекс GPT',
      installed: 'Установлено',
    },
    claude: {
      title: 'Claude',
      installed: 'Установлено',
    },
    perplexity: {
      title: 'Perplexity',
      installed: 'Установлено',
    },
    qwen: {
      title: 'Qwen',
      installed: 'Установлено',
    },
    deepseek: {
      title: 'Deepseek',
      installed: 'Установлено',
    },
    custom_llm: {
      title: 'Своя LLM',
    },
    mcp: {
      title: 'MCP Серверы',
      add: 'Добавить MCP сервер',
      edit: 'Редактировать MCP сервер',
      inherited: 'MCP серверы (унаследованные)',
    },
    rpc: {
      title: 'RPC Интеграции',
      add: 'Добавить RPC интеграцию',
      edit: 'Редактировать RPC интеграцию',
      inherited: 'RPC интеграции (унаследованные)',
    },
    installed: 'Установлено',
    inherited: 'Унаследовано',
    inheritedNote: 'Нажмите для редактирования на уровне приложения',
    workflowScope: {
      label: 'Область сценария',
      userLevel: 'Все сценарии (уровень пользователя)',
      description: 'Выберите, применяется ли интеграция ко всем сценариям или только к текущему',
      descriptionUserLevel: 'Интеграции применяются ко всем создаваемым сценариям',
      descriptionWorkflow: 'Интеграции применяются только к этому сценарию, переопределяя глобальные настройки',
    },
  },

  dialog: {
    integration: {
      title: 'Доступные интеграции',
      apiKey: 'API-ключ',
      folderId: 'ID папки',
      model: 'Модель',
      otherSettings: 'Другие настройки',
      saveSuccess: 'Изменения интеграции успешно применены!',
      deleteSuccess: 'Интеграция удалена',
      authenticationError: 'Проверьте ваш API-ключ и его действительность',
      genericError: 'Что-то пошло не так. Проверьте сетевые журналы в инструментах разработчика браузера',
      rateLimitExceeded: 'Превышена квота. Проверьте план и данные оплаты',
      serverError: 'Модель или сервер перегружены. Попробуйте позже',
      wrongRequest: 'Ошибка запроса. Проверьте сетевой журнал',
      noAccess: 'Нет доступа к {model}',
      wrongFolderId: 'Проверьте ID папки',
      alias: 'Псевдоним',
      transport: 'Транспорт',
      protocol: 'Протокол',
      description: 'Описание',
      toolName: 'Название инструмента',
      toolInputField: 'Поле ввода инструмента',
      command: 'Команда',
      arguments: 'Аргументы',
      serverUrl: 'URL сервера',
      timeout: 'Таймаут (мс)',
      host: 'Хост',
      port: 'Порт',
      username: 'Имя пользователя',
      privateKey: 'Приватный ключ',
      passphrase: 'Пароль ключа',
      commandTemplate: 'Шаблон команды',
      workingDirectory: 'Рабочая директория',
      url: 'URL',
      method: 'Метод',
      headers: 'Заголовки',
      bodyTemplate: 'Шаблон тела запроса',
      outputFormat: 'Формат вывода',
      outputField: 'Поле вывода',
      sessionIdField: 'Поле ID сессии',
      environmentVariables: 'Переменные окружения',
      autoApproveMode: 'Режим автоподтверждения',
      allowedTools: 'Разрешённые инструменты',
      requiredField: 'Обязательное',
      optionalField: 'Необязательное',
      deleteConfirmTitle: 'Удалить интеграцию',
      deleteConfirmMessage: 'Удалить "{alias}"? Это действие необратимо.',
      editAction: 'Редактировать интеграцию',
      deleteAction: 'Удалить интеграцию',
      claudePreset: 'Пресет Claude CLI',
    },
  },

  apiRootUrl: 'URL корня API',
  maxTokens: 'Макс. токенов',
  apiType: 'Тип API',
  embeddingsChunkSize: 'Размер чанка эмбеддингов',
  customLLMHint: 'Подсказка: используйте команду `/custom` для этой интеграции',

  profileSettings: {
    applyChanges: 'Применить изменения',
    emailAddress: 'Адрес электронной почты',
    editProfile: 'Редактировать профиль',
    appsIntegrations: 'Интеграции',
    username: 'Имя пользователя',
    success: 'Успешно',
    unknown: 'Неизвестно',
    model: 'Модель',
  },

  defaultLang: 'Авто по языку системы',
  noLanguage: 'Язык не найден',
  default: 'По умолчанию',
  lang: 'Язык',

  langSaveSuccessfully: 'Язык успешно сохранён',
  modelSaveSuccessfully: 'Модель успешно сохранена',

  themeLabel: 'Тема',
  themeLight: 'День',
  themeDark: 'Ночь',
  themeSystem: 'Авто по ОС',

  createWorkflow: 'Создать сценарий',
  callToRegisterTitle: 'Создайте свои сценарии',
  buttonRegister: 'Зарегистрироваться бесплатно',

  homePublicText: 'Публичные сценарии',
  homePrivateText: 'Мои сценарии',
  workflowTemplates: 'Мои шаблоны',
  createWorkflowFromTemplate: 'Создать сценарий из шаблона',
  tabAll: 'Все',
  tabPrivate: 'Личные',
  tabPublic: 'Публичные',
  tabPublicUnlisted: 'Скрытые',

  workflowTitle: 'Название',
  workflowShared: 'Общий',
  workflowCreating: 'Создание нового сценария',
  workflowLoading: 'Загрузка сценария',
  workflowIsPublic: 'Публичный',
  workflowCardCreated: 'создан',
  workflowCardUpdated: 'обновлён',
  workflowCardTimeAgo: 'назад',
  menuDeleteWorkflow: 'Удалить',
  menuExportWorkflow: 'Экспорт',
  menuVisibility: 'Видимость',
  workflowAddCategoryLabel: 'Добавить категорию',
  workflowAddDashboardLabel: 'Добавить дашборд',

  dialogWorkflowPrivacyOpenerTitle: 'Изменить видимость',
  dialogWorkflowPrivacyMessage: 'Выберите, как другие могут найти и просмотреть ваш сценарий:',
  dialogWorkflowPrivacyTitle: 'Доступ и видимость',
  buttonShare: 'Публичный',
  buttonShareWritable: 'Публичный с правом редактирования',
  buttonShareWritableMessage: 'Все могут редактировать (только для администраторов)',
  buttonShareWritableHidden: 'Публичный скрытый с правом редактирования',
  buttonShareWritableHiddenMessage: 'Все с ссылкой могут редактировать',
  buttonShareMessage: 'Все могут найти в списке публичных сценариев',
  buttonShareHidden: 'Публичный скрытый',
  buttonShareHiddenMessage: 'Все с ссылкой могут просматривать',
  buttonUnshare: 'Личный',
  buttonUnshareMessage: 'Только вы можете просматривать',
  shareSuccessChange: 'Видимость сценария успешно изменена',
  categoryCreatedSuccesfully: 'Категория сценария успешно создана',
  workflowDeleteSuccessful: 'Сценарий успешно удалён',

  delete: 'Удалить',
  deleteWorkflowWarning: 'Для подтверждения введите "{title}" ниже:',
  deleteWorkflowMessage: 'Это действие необратимо. Подтвердите, введя название сценария',
  deleteWorkflowDialogTitle: 'Удалить сценарий?',

  noWorkflowsYet: 'Пока нет сценариев',
  updated: 'Обновлён',
  created: 'Создан',
  workflowIsHidden: 'Публичный скрытый',
  workflowIsPrivate: 'Личный',
  searchWorkflow: 'Поиск сценария',
  workflowsPublic: 'Публичные сценарии',
  workflowsPrivate: 'Мои сценарии',
  emptyWorkflow: 'Пустой сценарий',
  createNewWorkflow: 'Создать новый сценарий',
  prev: 'Предыдущая',
  next: 'Следующая',
  actions: 'Действия',
  downloadCSV: 'Скачать CSV',
  morePages: 'Больше страниц',
  userSettingsMenuSignedIn: 'Вошли',
  logout: 'Выйти',
  surveyData: 'Данные опроса',
  workflowId: 'Сценарий (Id)',
  close: 'Закрыть',

  settingsPageProfile: 'Профиль',
  settingsPageIntegrations: 'Интеграции',
  loadingPlaceholder: 'Загрузка...',
  toggleSidebar: 'Переключить боковую панель',
  toggleSecondaryMenu: 'Переключить вторичное меню',
  rowsPerPage: 'Строк на странице',
  page: 'Страница',

  copy: 'Копировать',
  copied: 'Скопировано!',

  share: 'Поделиться',
  shareWorkflow: 'Поделиться сценарием',
  shareWorkflowTitle: 'Поделиться сценарием',
  shareWorkflowDescription: 'Поделитесь сценарием по ссылке или QR-коду',
  shareLink: 'Ссылка',
  showQRCode: 'Показать QR-код',
  hideQRCode: 'Скрыть QR-код',
  downloadQRCode: 'Скачать QR-код',
  advancedOptions: 'Дополнительные параметры',
  visibilityLabel: 'Видимость',
  visibilitySettings: 'Видимость и доступ',
  visibilityPublic: 'Публичный',
  visibilityPrivate: 'Личный',
  visibilityUnlisted: 'Скрытый',
  visibilityPrivateDescription: 'Только вы можете просматривать этот сценарий',
  visibilityUnlistedDescription: 'Все с ссылкой могут просматривать',
  visibilityPublicDescription: 'Доступен и виден всем',
  collaborativeEditing: 'Совместное редактирование',
  collaborativeEditingUnlistedDescription: 'Все с ссылкой могут редактировать',
  collaborativeEditingPublicDescription: 'Все могут редактировать',
  workflowSharedPublicSuccess: 'Сценарий теперь публичный! Ссылка скопирована.',
  workflowMadePrivateSuccess: 'Сценарий теперь личный',

  workflowTree: {
    title: 'Дерево сценария',
    nodeDetails: 'Детали узла',
    selectNode: 'Выберите узел из дерева для просмотра деталей',
    errorTitle: 'Ошибка загрузки сценария',
    retry: 'Повторить',
    rootNodeDefault: 'Корневой узел',

    empty: {
      title: 'Нет узлов',
      description: 'Создайте первый узел для начала работы',
      createFirst: 'Создать первый узел',
    },

    node: {
      settings: 'Настройки',
      command: 'Команда',
      commandPlaceholder: 'Введите команду...',
      execute: 'Выполнить',
      executing: 'Выполняется...',
      abort: 'Прервать',
      addChild: 'Добавить дочерний',
      addSibling: 'Добавить соседний',
      close: 'Назад',
      duplicate: 'Дублировать',
      untitled: 'Без названия',
      rename: 'Переименовать',
      editHint: 'Двойной клик для редактирования',
      preview: 'Предпросмотр',
      previewError: 'Ошибка предпросмотра',
      refineCostHint: '⚡ ~{cost} LLM {cost, plural, one {вызов} few {вызова} other {вызовов}}',
      refineCostOverLimit: '⛔ Превышен :limit= — будет отклонено ({cost} вызовов)',
      commodityCeilingHint:
        '⚠ Только структурная проверка: отклоняются пустые, отказные и упавшие ответы. Мягкие ошибки (правдоподобный текст через HTTP 200) неотличимы от корректного вывода на этом уровне — используйте /refine + /validate для семантической проверки.',
      suppressedRunHint:
        '⚠ Один запуск — best-of-N подавлен для команды с побочными эффектами (запрошено :n={n}). Запуск {n} раз выполнил бы {n} реальных внешних операций.',
      refineChildSuppressedHint:
        '⚠ Дочерняя команда с побочными эффектами пропущена внутри форков /refine — при запуске на каждый форк выполнялись бы N реальных внешних операций.',
      retryWithheldHint:
        '⚠ Повтор удержан — родительская команда имеет побочные эффекты; запрошено :retry={n}, но повтор продублировал бы внешнюю операцию.',
      verdictButton: 'Показать вердикт',
    },

    verdictDrawer: {
      title: 'Вердикт по критериям',
      winnerLabel: '(победитель)',
      criterionLabel: 'Критерий',
      rankingsLabel: 'Рейтинг форков',
      forkLabel: 'Форк {index}',
      rankLabel: '#{rank}',
      winnerEvidenceLabel: 'Победитель занял #{rank} из {total} по этому критерию',
      modeStrict: 'строгий',
      modeFallback: 'резервный',
      modeLabel: 'Режим: {mode}',
      eligibleLabel: '{eligible} из {total} форков прошли',
      noSignalWarning: 'Рейтинги жюри не собраны — победитель выбран по позиции',
      tiebreakWarning: 'Победитель выбран по правилу тай-брейка — кросс-семейный рейтинг не был решающим',
      judgeQualityWarningsTitle: 'Предупреждения о качестве судьи',
      judgeQualityWarning_singleProvider:
        'Настроен один провайдер — кросс-семейная оценка невозможна; судья наследует смещение генератора',
      judgeQualityWarning_lowestTierOnly: 'Настроены только модели низшего уровня — граница надёжности слабая',
      judgeQualityWarning_juryDuplicates:
        'Размер жюри превышает число семейств — некоторые члены жюри из одного семейства',
      judgeQualityWarning_fallbackWithWeakJudge:
        'Резервный режим со слабым судьёй — ухудшенный вывод принят со сниженной достоверностью',
      judgeQualityWarning_noReasoningMode: 'Нет модели с режимом рассуждений — оценка без расширенного анализа',
      judgeQualityWarning_allGateFiltered:
        'Все кандидаты структурно отклонены — fallback не исправит пустой вывод или отказ',
      judgeQualityWarning_degradedInput:
        'Бюджет токенов на форк слишком мал для оценки полного контекста — судья ранжирует усечённые данные; достоверность снижена',
      judgeQualityWarning_commodityPartialSuccess:
        'Часть параллельных форков завершилась ошибкой — результат отражает только успешные форки; частичное выполнение',
      judgeQualitySeverityHigh: 'высокий',
      judgeQualitySeverityMedium: 'средний',
      judgeQualitySeverityLow: 'низкий',
      modeCommodity: 'товарный',
      commodityLabel: '{eligible} из {total} форков выполнены успешно',
      commodityPartialWarning:
        'Частичный успех — {eligible} из {total} форков дали результат; {failed} завершились с ошибкой',
      fallbackUsedLabel:
        'Резервный победитель выбран принудительно — ни один форк не прошёл основные критерии; выбран наименее плохой',
      noWinnerLabel: 'Победитель не выбран',
      generatorOnlyJudgeLabel:
        'Генератор и судья используют одного провайдера — независимость между семействами моделей недостижима',
      judgeReasoningRequestedLabel: 'Запрошено расширенное рассуждение судьи (:judge_reasoning)',
      modeInvalid: 'недопустимый',
      modeSuppressed: 'подавленный',
      failureCauseMissingParent:
        'Эта команда требует родительской ячейки — добавьте её ниже существующей ячейки рабочего процесса',
      failureCauseInvalidCriteria:
        'Критерий /validate пуст — добавьте текст критерия в команду /validate перед запуском',
      commodityAllFailedWarning:
        'Все {total} параллельных форков завершились с ошибкой — проверьте доступность провайдера и повторите попытку',
    },

    discardedForks: {
      title: 'Запуски форков',
      forkLabel: 'Форк {index}',
      totalLabel: '{total} форков',
      statusPending: 'выполняется…',
      status_ok: 'прошёл',
      status_selected: 'выбранный победитель',
      'status_criteria-failed': 'критерий не выполнен',
      'status_runtime-failed': 'ошибка',
      failedAt: 'критерий: {criterion}',
      attempts: '{count} попыток',
      selectionLabel: '{eligible} из {total} форков допущены; выбор: {layer}',
      failureCauseLabel: 'ошибка: {cause}',
      judgeInputLabel: 'судья сравнил {count} кандидатов; бюджет на форк {budget} символов',
      discardedForksButton: 'Показать форки',
    },

    status: {
      saving: 'Сохранение...',
      unsaved: 'Несохранённые изменения',
      saved: 'Сохранено',
    },

    deleteDialog: {
      title: 'Удалить узел',
      descriptionWithChildren:
        'Удалить «{title}» и {count} {count, plural, one {дочерний узел} few {дочерних узла} other {дочерних узлов}}? Это действие необратимо.',
      description: 'Удалить «{title}»? Это действие необратимо.',
      descriptionMultipleWithChildren:
        'Удалить {nodeCount} {nodeCount, plural, one {узел} few {узла} other {узлов}} и {descendantCount} {descendantCount, plural, one {дочерний узел} few {дочерних узла} other {дочерних узлов}}? Это действие необратимо.',
      descriptionMultiple:
        'Удалить {nodeCount} {nodeCount, plural, one {узел} few {узла} other {узлов}}? Это действие необратимо.',
    },

    mutation: {
      invalidNodeData: 'Некорректные данные узла',
      rootExists: 'Корневой узел уже существует',
      rootWithParent: 'Корневой узел не может иметь родителя',
      parentNotFound: 'Родительский узел не найден',
      nodeNotFound: 'Узел не найден',
      cannotRemoveRoot: 'Нельзя удалить корневой узел',
      circularReference: 'Перемещение создаст циклическую ссылку',
      cannotMoveRoot: 'Нельзя переместить корневой узел',
      targetNotFound: 'Целевой узел не найден',
      noTargetParent: 'Нельзя дублировать корень без целевого родителя',
      selfParent: 'Узел не может быть собственным родителем',
      failed: 'Операция не выполнена',
      bulkDeletePartial: '{removed} удалено, {skipped} пропущено (используются)',
    },
  },
}
