export { default as delta5Logo } from './delta5-logo.webp'
export { default as ClaudeLogo } from './claude.webp'
export { default as CustomLLMLogo } from './custom.webp'
export { default as DeepseekLogo } from './deepseek.webp'
export { default as OpenaiLogo } from './openai.webp'
export { default as PerplexityLogo } from './perplexity.webp'
export { default as QwenLogo } from './qwen.webp'
export { default as YandexGPTLogo } from './yandex_gpt.webp'
export { default as GoogleDriveLogo } from './google_drive.webp'

export * from './templatePictures'
