export const buildBwrapArgs = (command, args, {systemDirArgs, bindPaths, allowNetwork = false}) => [
  '--unshare-pid',
  '--unshare-uts',
  '--unshare-ipc',
  ...(allowNetwork ? [] : ['--unshare-net']),
  '--proc',
  '/proc',
  '--dev',
  '/dev',
  '--tmpfs',
  '/tmp',
  ...systemDirArgs,
  ...bindPaths.flatMap(p => ['--ro-bind', p, p]),
  '--',
  command,
  ...(args ?? []),
]
