export const SIDEBAR_LAYOUT = {
  PRIMARY_WIDTH: 72,
  PRIMARY_HEADER_HEIGHT: 56,
  PRIMARY_BUTTON_SIZE: 48,
  PRIMARY_PADDING: 12,
  SECONDARY_HEADER_HEIGHT: 56,
  SECONDARY_WIDTH: 264,
} as const

export const MOBILE_BREAKPOINT = 768
